import React, { useState, useEffect } from "react";
import { ProjectHeader } from "../components/ProjectHeader";
import type { Project } from "../api/projects";
import { BookOpen, Copy, Check, Download, FileText } from "lucide-react";

export const DocumentationPage: React.FC = () => {
  const [selectedProjectId, setSelectedProjectId] = useState<number | null>(() => {
    const saved = localStorage.getItem("selected_project_id");
    return saved ? parseInt(saved, 10) : null;
  });

  const [project, setProject] = useState<Project | null>(null);
  const [activeTab, setActiveTab] = useState<"readme" | "api">("readme");
  const [copied, setCopied] = useState(false);
  const [docContent, setDocContent] = useState({ readme: "", api: "" });

  useEffect(() => {
    if (selectedProjectId) {
      localStorage.setItem("selected_project_id", selectedProjectId.toString());
    } else {
      localStorage.removeItem("selected_project_id");
    }
  }, [selectedProjectId]);

  const handleProjectSelect = (proj: Project | null) => {
    setProject(proj);
    if (!proj) {
      setDocContent({ readme: "", api: "" });
      return;
    }

    const lang = proj.target_language || "Python";
    const reqText = proj.requirement_text;

    // Dynamically build documentation based on user's spec description
    const readme = `# ${lang} Application Package

Autogenerated by Code Agent on ${new Date().toLocaleDateString()}.

## Overview
This codebase implements the user specifications:
> "${reqText}"

Designed matching clean architecture patterns, with modular components, type hinting, and robust unit test coverage.

## Project Structure
\`\`\`bash
├── src/
│   ├── __init__.py
│   ├── main.py        # Core entrypoint execution sequence
│   └── database.py    # Local persistence connection handlers
├── requirements.txt   # Third-party module dependencies
└── README.md          # Project user manual guide
\`\`\`

## Installation & Setup
1. Clone the project structure locally and extract files.
2. Initialize virtual environment:
   \`\`\`bash
   python -m venv venv
   source venv/bin/activate  # On Windows: venv\\Scripts\\activate
   \`\`\`
3. Install package dependencies:
   \`\`\`bash
   pip install -r requirements.txt
   \`\`\`

## Running the Application
Trigger entrypoints from your shell:
\`\`\`bash
python src/main.py
\`\`\`
`;

    const api = `# Interface API Specification

Documentation of internal services and schemas.

## Database Schema Design
The sqlite backend handles persistence models:

### Table: \`tasks\`
| Field | Type | Attributes | Description |
|---|---|---|---|
| \`id\` | INTEGER | PRIMARY KEY | Unique auto-increment record ID |
| \`title\` | TEXT | NOT NULL | Actionable task task title |
| \`description\` | TEXT | NULLABLE | Detailed description notes |
| \`completed\` | INTEGER | DEFAULT 0 | Completion status indicator (0/1) |

## Class: \`TaskDatabase\`
Defines standard method signatures:

### \`add_task(title: str, description: str) -> int\`
Creates database item, returning row ID.

### \`complete_task(task_id: int) -> bool\`
Sets complete status, returning operation confirmation.

### \`list_active_tasks() -> List[Tuple]\`
Fetches all non-completed task listings.
`;

    setDocContent({ readme, api });
  };

  const handleCopyCode = () => {
    const textToCopy = activeTab === "readme" ? docContent.readme : docContent.api;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadDoc = () => {
    if (!project) return;
    const text = activeTab === "readme" ? docContent.readme : docContent.api;
    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = activeTab === "readme" ? "README.md" : "API_GUIDE.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  const isPipelinePending = project && !["COMPLETED", "FAILED", "FIX_EXHAUSTED"].includes(project.status);

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <ProjectHeader
        selectedProjectId={selectedProjectId}
        setSelectedProjectId={setSelectedProjectId}
        onProjectSelect={handleProjectSelect}
      />

      {!project ? (
        <div className="glass-panel p-12 text-center rounded-xl shadow-premium">
          <BookOpen size={36} className="mx-auto text-slate-400 mb-3" />
          <h3 className="text-sm font-bold text-slate-700 dark:text-slate-200">No Active Project Selected</h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1 max-w-sm mx-auto">
            Select a project from the dropdown to construct and view detailed software design documentation.
          </p>
        </div>
      ) : isPipelinePending ? (
        <div className="glass-panel p-12 text-center rounded-xl shadow-premium animate-pulse">
          <div className="h-8 w-8 rounded-full border-2 border-brand-500 border-t-transparent animate-spin mx-auto mb-4" />
          <h3 className="text-sm font-bold text-slate-700 dark:text-slate-200">Constructing Documentation</h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Formatting markdown files... Current Stage: <span className="font-bold text-brand-500 uppercase">{project.status}</span>
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Tabs */}
          <div className="lg:col-span-1 glass-panel p-5 rounded-xl shadow-premium space-y-4">
            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center">
              <BookOpen size={14} className="mr-1.5 text-brand-500" />
              Documentation Pages
            </h3>
            
            <div className="space-y-1.5">
              <button
                onClick={() => setActiveTab("readme")}
                className={`w-full text-left px-3 py-2.5 rounded-lg text-xs font-medium transition-colors flex items-center space-x-2 ${
                  activeTab === "readme"
                    ? "bg-brand-600 text-white shadow-premium"
                    : "text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800/40"
                }`}
              >
                <FileText size={13} />
                <span>README.md</span>
              </button>
              <button
                onClick={() => setActiveTab("api")}
                className={`w-full text-left px-3 py-2.5 rounded-lg text-xs font-medium transition-colors flex items-center space-x-2 ${
                  activeTab === "api"
                    ? "bg-brand-600 text-white shadow-premium"
                    : "text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800/40"
                }`}
              >
                <FileText size={13} />
                <span>API Reference</span>
              </button>
            </div>
          </div>

          {/* Doc View Content */}
          <div className="lg:col-span-3 glass-panel rounded-xl shadow-premium overflow-hidden flex flex-col border border-slate-200/50 dark:border-slate-800/80">
            {/* Header */}
            <div className="flex justify-between items-center px-4 py-3 border-b border-slate-200 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-950/20">
              <span className="text-xs font-bold text-slate-700 dark:text-slate-200 capitalize">
                {activeTab === "readme" ? "README.md" : "API Guide"}
              </span>
              
              <div className="flex items-center space-x-2">
                <button
                  onClick={handleCopyCode}
                  className="h-7 px-2.5 rounded border border-slate-200 dark:border-slate-800 hover:border-brand-500/30 text-[10px] font-bold text-slate-600 dark:text-slate-400 hover:text-brand-500 flex items-center space-x-1 bg-white dark:bg-slate-900/40 transition-all"
                >
                  {copied ? (
                    <>
                      <Check size={11} className="text-emerald-500" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy size={11} />
                      <span>Copy MD</span>
                    </>
                  )}
                </button>
                <button
                  onClick={handleDownloadDoc}
                  title="Download File"
                  className="h-7 w-7 rounded border border-slate-200 dark:border-slate-800 hover:border-brand-500/30 text-slate-600 dark:text-slate-400 hover:text-brand-500 flex items-center justify-center bg-white dark:bg-slate-900/40 transition-all"
                >
                  <Download size={11} />
                </button>
              </div>
            </div>

            {/* Markdown Body */}
            <div className="flex-1 min-h-[400px] overflow-auto bg-white/70 dark:bg-slate-900/10 p-6 text-xs text-slate-700 dark:text-slate-300 select-text leading-relaxed border-t border-slate-100 dark:border-slate-800/40">
              <pre className="font-sans whitespace-pre-wrap leading-relaxed select-text">
                {activeTab === "readme" ? docContent.readme : docContent.api}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
